- recipe/meta.yaml
> pin style changes [skip ci]

- recipe/meta.yaml
- recipe/run_test.sh
Ping @czender it would be nice to add those 3-commands you mentioned in https://github.com/conda-forge/nco-feedstock/pull/5#issuecomment-225577109 as an extra test in this PR. (`conda-build` run any python or bash script named `run_test.{sh,py}` in the test phase.)
> Add ESMF run-time dependency.

- .travis.yml
- LICENSE
- ci_support/run_docker_build.sh
- recipe/meta.yaml
- recipe/run_test.sh
See http://nco.sourceforge.net/ANNOUNCE
> Update to 4.6.4

- recipe/meta.yaml
See https://github.com/nco/nco/releases/tag/4.6.5
> Update to 4.6.5

- .travis.yml
- ci_support/fast_finish_ci_pr_build.sh
- ci_support/run_docker_build.sh
- circle.yml
- recipe/meta.yaml
See http://nco.sourceforge.net/ANNOUNCE
> Update to 4.6.6

- recipe/meta.yaml
> add openblas

- ci_support/run_docker_build.sh
- recipe/meta.yaml
Issuing the PR from Linux now 😄
> update to 4.6.7

- recipe/meta.yaml
Update the feedstock to nco 4.6.8
> update to nco 4.6.8

- recipe/meta.yaml
> Update NCO recipe to v 4.7.0

- recipe/meta.yaml
Just in case we end up putting newer ANTLRs in antlr-feedstock...
🔗 https://github.com/conda-forge/staged-recipes/pull/4559
🔗 https://github.com/sympy/sympy/pull/13706
> Pin antlr dependency

- recipe/meta.yaml
See https://github.com/nco/nco/releases/tag/4.7.3
> update to 4.7.3

- recipe/meta.yaml
Supersedes https://github.com/conda-forge/nco-feedstock/pull/66
> update to 4.7.5

- recipe/meta.yaml
See https://github.com/conda-forge/nco-feedstock/issues/34#issuecomment-401180641
> update libnetcdf pin

- .ci_support/linux_mpimpich.yaml
- .ci_support/linux_mpinompi.yaml
- .ci_support/linux_mpiopenmpi.yaml
- .ci_support/osx_mpimpich.yaml
- .ci_support/osx_mpinompi.yaml
- .ci_support/osx_mpiopenmpi.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015vc14.yaml
- recipe/meta.yaml
> nco v4.9.1

- .ci_support/linux_64_.yaml
- .ci_support/migrations/expat23.yaml
- .ci_support/migrations/libnetcdf480.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- build-locally.py
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/run_test.bat
- recipe/run_test.sh
Checklist
This adds tests to verify UDUnits is invoked correctly in Conda NCO distributions. Behavior on Compy leads me to suspect otherwise.
After verifying/solving UDUnits issues, will move on to OpenMP on MacOS/Windows
> Add UDUnits tests to dev branch

- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.bat
- recipe/run_test.sh
Checklist
I'm going to do a first build with `libnetcdf` 4.8.0 in case anyone needs it, then update to 4.8.0 in another PR.
> Update to 4.9.9

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Make czender a maintainer

- recipe/build.sh
- recipe/meta.yaml
> Disable openmp osx

- recipe/build.sh
- recipe/meta.yaml
> DEV: Update to 5.0.0-alpha03

- .azure-pipelines/azure-pipelines-linux.yml
- recipe/meta.yaml
> Update to 5.0.0

- .azure-pipelines/azure-pipelines-linux.yml
- recipe/meta.yaml
> DEV: Update to 5.0.1-alpha02

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
- recipe/run_test.sh
> DEV: update to 5.0.3beta01

- .ci_support/linux_64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
- recipe/run_test.sh
> update to v5.0.3

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/migrations/libnetcdf480.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- .gitattributes
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
> DEV: update to 5.0.4-beta0

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/osx_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> DEV: Udate to 5.0.5-beta02

- recipe/meta.yaml
> DEV: Update to 5.0.5-beta03

- LICENSE.txt
- recipe/meta.yaml
> DEV: update to v5.0.6-alpha02

- .ci_support/osx_64_.yaml
- LICENSE.txt
- recipe/meta.yaml
> Update to v5.0.6

- recipe/meta.yaml
> [DEV] Update to v5.8.0-beta02

- recipe/meta.yaml
> [DEV] Update to v5.8.0-beta03

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/migrations/hdf51121.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- .circleci/config.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- build-locally.py
- recipe/meta.yaml
> Update to 5.1.0

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
- recipe/run_test.sh
> [DEV] update to v5.1.1-alpha11

- recipe/meta.yaml
> [DEV] Update to 5.1.1-alpha12

- recipe/meta.yaml
> Update to 5.1.1-alpha13

- .ci_support/linux_64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Update to v5.1.1

- .azure-pipelines/azure-pipelines-win.yml
- .circleci/config.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
> [DEV] update to v5.1.2-beta01

- recipe/meta.yaml
> [DEV] Update to v5.1.2-beta01 (for reals this time)

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_arm64_.yaml
- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- conda-forge.yml
- recipe/build.sh
- recipe/meta.yaml
This merge brings over changes from `main` that were added to support osx-arm64 and other new architectures.
Checklist
> [DEV] update to 5.1.4-alpah05

- recipe/meta.yaml
> [dev] Update to 5.1.4-alpha06

- recipe/meta.yaml
> Update to v5.1.4

- recipe/meta.yaml
> Update to 5.2.3

- recipe/meta.yaml
> Update to v5.2.4
